### ISSUE TITLE
Alternative colours for Mint-Y like Mint-X has

### ISSUE THREAD

**Issue by s7jones** [linuxmint/mint-y-theme#11]
This theme is great but personally the default green motif is not for me, with the old theme I could change this and it would be great if Mint-Y was expanded to different colours like Mint-X supported.

Is it possible to do a batch recolouring of the icons?

**Comment by mtwebster** [comment]
I'm sure it'll be at least considered once the theme is considered solid and complete.  It's still a bit of a work in progress - the icons and ui themes alike.

**Comment by jwlighting** [comment]
I've spend some work on fork with a blue version. Not perfect but an option for those who really don't like the green: [https://github.com/jwlighting/mint-y-theme](url)
Feel free to fork and optimize it, pull requests are welcome!

**Comment by JosephMcc** [comment]
@jwlighting The link you posted seems to be dead.

**Comment by jwlighting** [comment]
@JosephMcc Thanks for your reply, i've fixed it

**Comment by erikdubois** [comment]
i am making a tutorial how to change the colours
and i found out (i think) you are missing a "make assets" script for cinnamon
Can this be correct?

**Comment by JosephMcc** [comment]
There is no need for "make assets" script for Cinnamon. The gtk theme uses an asset sheet that holds all the assets in a single svg file. That is why it has one. That isn't done for the Cinnamon theme. The light and dark assets are in separate folders as individual files and then copied to the appropriate theme in build-themes.py.

**Comment by erikdubois** [comment]
Hi JosephMcc
i made a another theme this time with grey accents instead of green. My third theme. Blue, Orange and now Grey.

But in the cinnamon folders (common-assets, dark-assets,menu, misc, panel) the icons are still all green. I fixed it each time by manually editing them.
What am I doing wrong?
If I analyze the code, I see no where that the icons are created - hence the question - is there an make asset script I do not see.
If the files are copied then where in the code. I do see this code
`            os.system("cp -R cinnamon/common-assets %s" % version_folder)
            os.system("cp -R cinnamon/light-assets %s" % version_folder)
            os.system("cp cinnamon/mint-y-thumbnail.png %s" % os.path.join(version_folder, "thumbnail.png"))
            os.system("cp cinnamon/cinnamon.css %s" % version_folder)`

But then where is the code that the newly created png's are moved to the cinnamon folders.
It is my believe that the cinnamon folder will always stay green. 
Maybe I am not seeing it but the cinnamon assets are never changed. The old ones are copied in the above code. I hope I am right about this. Time is scarse but I want to help.

**Comment by JosephMcc** [comment]
The code you posted is where it's being done. If you look at this line: https://github.com/linuxmint/mint-y-theme/blob/master/src/build-themes.py#L60
That line is copying the assets from the light assets folder in the src directory into the folder of the generated theme here: https://github.com/linuxmint/mint-y-theme/tree/master/usr/share/themes/Mint-Y/cinnamon

I'm not sure how you are producing the themes. Are you adding color variations into the existing src or are you making copies and creating a new src directory for each variation?

**Comment by erikdubois** [comment]
Hi, I have been making this post on youtube
https://www.youtube.com/watch?v=c4iC07eg6ck&list=PLlloYVGq5pS41WmxZtkmV_6Qo4haKzO-u&index=5
I basically change all the greens into another colour with a sed command.
This effects css and svg's alike.
https://github.com/erikdubois/Ultimate-Linux-Mint-18-Cinnamon/blob/master/Mint-Y-Theming/change-color.sh
I will make a personal youtube movie to tell you how I understand your script works lateron.

**Comment by erikdubois** [comment]
This is the movie - me trying to explain the issue
language can be a barrier
https://youtu.be/N2VWoSxo7f4

**Comment by JosephMcc** [comment]
Ok, so I watched your video. First off your english was totally fine. I think you are just misunderstanding how the theme is built. In the gtk2 and gtk3 themes there are assets sheets that hold the complete collection of image assets used in the themes. In the gtk3 theme this is assets.svg. The render-assets.sh then pulls the individual elements from the asset sheet and puts them in the assets folder which the build-themes.py script then copies to the proper theme variation. This part you have correct.

If you look in the src/cinnamon folder you will notice that there is no assets.svg asset sheet or render-assets.sh script. In the Cinnamon part of the theme the image assets are copied directly from the *-assets folders to the proper theme variation. If you want to modify the assets for the Cinnamon theme you need to edit them directly in the *-assets folder. If you recolor those images and then run the build-themes.py you will get what you want. The items in the common-assets folder are copied to both the light and dark variations while the dark-assets and light-assets will go to the appropriate theme.

It just skips the step of turning an assets.svg asset sheet into the individual elements so it doesn't have the convenience of recoloring them in a single file.

**Comment by howdev** [comment]
There is no sense in this suggestion. Mint-x, Mint-Y is green, and must be green to reflect what it is. If Linux Mint is blue then what??? is going on. If you like other colour then choose other themes, there are modern ones that come with blue. I know there exit Mint theme in other colours that come with LinuxMint they should be named something else than Mint. The real colour issue why there are black icons and dark text in the dark panel. why is not fixed. in Mint 17.x or 18.1

**Comment by Draconicrose** [comment]
@howdev He means alternatives like Mint-X-Aqua (my preferred one!) which you can find by default in your themes.

**Comment by JosephMcc** [comment]
Thanks for the requests. This is something we plan to do at some point.
