### ISSUE TITLE
Shade, Menu and Sticky options missing

### ISSUE THREAD

**Issue by muzena** [linuxmint/mint-y-theme#15]
In Titlebar Shade, Menu and Sticky options are unavailable.
![shade](https://cloud.githubusercontent.com/assets/1978777/16077610/3f230042-32fa-11e6-9157-fb1e56ac4f2f.png)

**Comment by JosephMcc** [comment]
To be a bit more accurate it's missing shade, menu and sticky options.

**Comment by muzena** [comment]
@JosephMcc 
Yes I didn't noticed that this two options is missing too.
I don't understand Sticky option, what is her purpose, when I click on Sticky icon in titlebar notihing happens.

**Comment by JosephMcc** [comment]
"Sticking" a window means it will show on all workspaces.

**Comment by alxgvr** [comment]
Yes, there is no shadows. White background of a window merges with another window.

**Comment by JosephMcc** [comment]
@alxgvr did you post in the correct issue? Your comment makes no sense.

**Comment by Cos-mo** [comment]
There are 3 icons, that can be added to the title bar via window settings, but are not added by default.

Add them and you will find, that only Mint-X (and Crux) as control theme do show them. Mint-Y does not show any of them. (Other of the preinstalled themes show them partly but this is not the concern here, just for completeness.)

**Comment by JosephMcc** [comment]
Need to come up with a good design/style for them.

**Comment by Cos-mo** [comment]
I suggest for the beginning to use the icons from Mint-X - just as the Mint-Y icon theme is at now only a copy of Mint-X.
This would restore the full compatibility between Mint-Y and the Cinnamon feature regarding the title bar.

**Comment by NikoKrause** [comment]
@JosephMcc 
Maybe you find some good icons here: https://materialdesignicons.com/
I'm not sure if the license of the icons are compatible with Linux Mints, but JabRef is using them. 
But some of them look familiar to yours, e.g. close button.

Some themes are using for the menu icon the icon of the window.
For example the theme `Bright` is doing this.

Maybe you can do that for Mint-Y, but instead of using the original icon use a monochrome version of it.
So the menu button on a firefox window is represented by a monochrome firefox icon.

Downside of this idea is, that for every application you have to have a monochrome icon version.

**Comment by JosephMcc** [comment]
Thanks for the info. I don't think you can depend on an app providing a symbolic version of it's icon though.

**Comment by NikoKrause** [comment]
I feared so. Hope you find some gold ideas anyway.

**Comment by NikoKrause** [comment]
Are you still searching for symbols for this icons?
If yes, how about this icons for shade:
![shade-down](https://cloud.githubusercontent.com/assets/8415124/19840267/5f5db23a-9ef2-11e6-93f8-6e318d6676b0.png) ![shade-up](https://cloud.githubusercontent.com/assets/8415124/19840268/60cfa1aa-9ef2-11e6-83c8-ac847ddba7eb.png)

**Comment by NikoKrause** [comment]
And for sticky icons maybe a pushpin:
![bildschirmfoto vom 2016-10-30 22-50-25](https://cloud.githubusercontent.com/assets/8415124/19840376/6fd23ddc-9ef4-11e6-82f4-fe93f34b6988.png)

**Comment by NikoKrause** [comment]
Here are the pin icons from https://materialdesignicons.com/
![bildschirmfoto vom 2016-10-31 14-26-49](https://cloud.githubusercontent.com/assets/8415124/19856875/b45836f0-9f7b-11e6-93e2-962a6abcb374.png)

**Comment by NikoKrause** [comment]
Another suggestion for shade, based on an icon from the free icon pack from http://www.webalys.com/nova/
![window](https://cloud.githubusercontent.com/assets/8415124/19857056/74ecfb9e-9f7c-11e6-9052-eaf3f105b9ea.png) ![window2](https://cloud.githubusercontent.com/assets/8415124/19857058/770ca9b0-9f7c-11e6-97c9-a2cb9892289a.png)
