### ISSUE TITLE
Looks like windows xp in root mode.

### ISSUE THREAD

**Issue by SethDusek** [linuxmint/mint-y-theme#16]
Any application that is launched through gksu/sudo looks really weird in Mint-y. Here is a list of examples

![Driver Manager](http://i.shibe.ml/Qmd7oUQXKVb9VZP9S2DcFJAGzqt1a29WHwF8GRXuFLyQdr.png)
![Gedit](http://i.shibe.ml/QmQqcJWoR2e8dWjHKrBjjnCr6RqKK12EYb8amYD9tcMYoK.png)

And here's also a video showing what happens to gdebi when it asks for your password http://i.shibe.ml/QmZeUT7UiQt2toLjo7yKZtZsBpkzxrAGvTDyPRzJHhh2Vz.webm

And yes, I've confirmed, this only happens with the Mint-y theme when applications launch as root

**Comment by JosephMcc** [comment]
Distro, desktop environment, and gtk version?

**Comment by SethDusek** [comment]
Distro: Linux Mint 17.3
DE: Cinnamon
GTK: 3.10 or whatever comes with mint

**Comment by JosephMcc** [comment]
You need to install theme in /usr/share/themes to affect applications run as root. The theme is meant for Mint18 and gtk3.18 and isn't supported in Mint17.
