### ISSUE TITLE
GTK 3.20 Support?

### ISSUE THREAD

**Issue by tristan957** [linuxmint/mint-y-theme#18]
I feel like this theme is gaining traction quickly and is the best Arc variant in my opinion. Granted I'm on Mint right now, but support for 3.20 would most likely increase usage and popularity. I know a ton of people would appreciate if this theme kept up with the current GTK version.

**Comment by JosephMcc** [comment]
I'm glad you enjoy the theme. Keeping it up to date isn't likely to happen unless we need to for Mint though. Part of the reason we use the lts base is so we don't have to fix the things that gnome releases break every six months.

**Comment by nicman23** [comment]
as i do not follow mint releases can I humbly ask when will this be updated to .20 (and beyond)

**Comment by JosephMcc** [comment]
Only when it's needed for Mint. Mint is an LTS based distro so it's on 3.18 for two years. The next thing it would likely be updated for is LMDE3 whenever the next debian stable is released.

**Comment by nicman23** [comment]
thanks :)
