### ISSUE TITLE
Mint-Y MDM Theme

### ISSUE THREAD

**Issue by tristan957** [linuxmint/mint-y-theme#19]
Currently there is a Mint-X theme, but I think a Mint-Y theme would look really good.

**Comment by JosephMcc** [comment]
This probably belongs here: https://github.com/linuxmint/mint-mdm-themes

**Comment by tristan957** [comment]
I will submit a feature request. Thanks for the link.
On Jun 30, 2016 12:35 PM, JosephMcc <notifications@github.com> wrote:This probably belongs here: https://github.com/linuxmint/mint-mdm-themes
