### ISSUE TITLE
Tool bar items don't have padding

### ISSUE THREAD

**Issue by dsandstrom** [linuxmint/mint-y-theme#2]
Using mint-y-theme-git from AUR and Cinnamon 3.0.1-2.  In some applications, the tool bar items don't have padding.  This is present in Nemo and pavucontrol.  The background is also, not always the same color.  Let me know if you need screen shots.

**Comment by JosephMcc** [comment]
Since you are on Arch I assume you are using gtk3.20?

**Comment by dsandstrom** [comment]
Yes, I figured that was the difference.  Arc has been updated to fix this problem, so I'm using their light controls, but your border, icons, and desktop.  Nice work so far.

**Comment by JosephMcc** [comment]
Ok. The theme is designed for Mint which will be on gtk3.18 for some time. 3.20 brought a lot of theme related changes. If someone is maintaining this for Arch in the AUR it's going to be up to them to keep it fixed and up to date.

**Comment by stefan-niedermann** [comment]
Just as a note - I am using Debian stretch (they use GTK 3.22) and i experience the same issue. No paddings at all which makes the theme unusable at all.  I know it was designed for Mint but i would really appreciate to be able to use it with one or tow gtk-versions up ;-)

Though great work :+1:

**Comment by JosephMcc** [comment]
It will get support at some point. Either for Mint19 or LMDE3. Whichever comes first.
