### ISSUE TITLE
Unmaximized windows when using the Mint-Y theme have window controls with a different spacing from the edge than their maximized counterparts.

### ISSUE THREAD

**Issue by tristan957** [linuxmint/mint-y-theme#20]
I thought the window controls seemed a little off on unmaximized windows so I brought out a screen ruler and compared Mint-Y to the Arc theme. I don't think I'm crazy and I don't think that this was intended. Hopefully the pictures below can explain this better.

Here is the Mint-Y theme applied to gnome-terminal unmaximized:
![mint-y](https://cloud.githubusercontent.com/assets/11936772/16472021/7f010466-3e26-11e6-9bb6-6381444a894c.png)

Here is the Arc theme applied to gnome-terminal unmaximized:
![arc](https://cloud.githubusercontent.com/assets/11936772/16472033/993a2e8e-3e26-11e6-92d1-43e1d3b6f215.png)

Finally here is the Mint-Y theme applied to a maximized window which seems to have the same spacing as the Arc theme:
![mint-y full](https://cloud.githubusercontent.com/assets/11936772/16472040/adec39d0-3e26-11e6-8914-83cd6b9ddd7d.png)

What you should look at are the pixel differences between the 2 themes and size of windows. Between each picture of Mint-Y and Arc unmaximized I kept the ruler and window in the same place so that they could be constants. I hope this helps! Doesn't seem to be more than a few pixels.

**Comment by tristan957** [comment]
@JosephMcc I want to make sure you've seen this.

**Comment by JosephMcc** [comment]
I have. Just haven't had the chance to mess with it yet.

**Comment by tristan957** [comment]
Ah when you get the chance then :)
