### ISSUE TITLE
Contrast Issues in Applications

### ISSUE THREAD

**Issue by MavropaliasG** [linuxmint/mint-y-theme#21]
Hello,

In Linux Mint 18 Cinnamon dark-y theme, in some dialogues or windows the contrast between the font and the background is very small and the text becomes indiscernible. Here are two examples I found in Opera and Kdenlive.

In Opera you can slightly see the dialog above the website that prompts you for remembering your password.

I'm sure there are more applications that have this issue, so I hope you can correct the class of the background/text that causes it and fix it globally.

Thanks

![screenshot from 2016-07-07 23-37-53](https://cloud.githubusercontent.com/assets/13523909/16659354/374d1db8-449c-11e6-94cb-bbd5a3f493cb.png)

![screenshot from 2016-07-07 23-38-28](https://cloud.githubusercontent.com/assets/13523909/16659366/3f476550-449c-11e6-82b9-7b3b954976c8.png)

**Comment by JosephMcc** [comment]
Don't know if there is anything to be done about this in the theme. Both browsers and qt applications are notoriously bad with full dark gtk themes. It's one of the main reasons why we have never included one by default in the past.

**Comment by ACinnamonUserInUK** [comment]
The same happens - and with the _standard_, not (just?) the dark Mint-Y theme, with Thunderbird menus, at least when particular themes (in happens with the popular Phoenity theme) are used. When I used the Mint-_X_ theme, there's no problem.

**Comment by jbmikk** [comment]
I really like this theme, it is very good and I have been waiting for something like this for very long.

However, broken inputs for most websites is a show stopper. I think this is a problem that goes beyond theme development. Web browsers should not use the native theme (at least not for page rendering), they should stick to their own default theme. 

Anyway, I think that waiting until all browsers and other applications fix their own problems, themes should try to be compatible. What if inputs had a lighter background, so the dark theme would be almost completely dark, except for input backgrounds.

Or maybe there could be two themes mint-y-dark, for hardcore people, and mint-y-almost-dark, for people who just want it to work.

**Comment by jbmikk** [comment]
It seems they are working to fix this in firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1216658

**Comment by JosephMcc** [comment]
As I said above. Qt applications and web browsers don't always play well with dark themes.
