### ISSUE TITLE
arc-firefox-theme

### ISSUE THREAD

**Issue by irondave** [linuxmint/mint-y-theme#22]
Use arc-firefox-theme as default firefox theme, maybe after modifying it to match with mint - y.

**Comment by JosephMcc** [comment]
We aren't going to mess with doing a firefox specific theme. It needs fixing and updating too often with the fast paced release schedule of firefox to be worth the trouble.

**Comment by irondave** [comment]
It's a specific theme but it was already done by horst3180 (https://github.com/horst3180/arc-firefox-theme)
Your job is modifying it to match with mint-y

**Comment by JosephMcc** [comment]
Once we choose to modify/maintain our own version that means we have to keep it up-to-date. It doesn't matter who made the original at that point. Not going to mess with something that is going to need updating every couple weeks.

**Comment by irondave** [comment]
Understood.
