### ISSUE TITLE
Why not installable for LMDE via "More Themes from the Web"?

### ISSUE THREAD

**Issue by stefan-niedermann** [linuxmint/mint-y-theme#23]
Hey guys,

thank you for this theme, it looks really great. I am running LMDE Betsy and i just had a look in the "Theme-Store" (The one which seems to be based on cinnamon.linuxmint.com). Unfortunately i couldn't find mint-y. Will it be populated there or do i have to manually install it?

Regards

**Comment by JosephMcc** [comment]
The site you are talking about is for third party themes. Mints official themes have never been there. Mint-Y is an entire package meaning gtk2, gtk3, metacity, cinnamon, etc. Some parts of it won't work correctly on LMDE. For right now the best way to get the cinnamon version is to get it from here.

**Comment by stefan-niedermann** [comment]
ah, thanks. and what is the name of the package i have to install to get the theme?

**Comment by JosephMcc** [comment]
It's not available in Betsy. The Cinnamon theme would work but the gtk theme isn't compatible with the version of gtk in LMDE2.

**Comment by stepanov-valentin** [comment]
I just do fresh install of LMDE, and install mint-y theme package from mint main repo. And all seems good. 
![screenshot from 2016-07-21 20 37 13](https://cloud.githubusercontent.com/assets/7223115/17032624/eed507d4-4f82-11e6-8885-56d0a4de44e0.png)

**Comment by JosephMcc** [comment]
It may seem that way but you will find it isn't. For example, do you have any scrollbars in Nemo?

**Comment by lagerspetz** [comment]
I am on LMDE2 using Mate. I have installed mint-y-theme from here just now ( commit a0344c6b263bdf8dcdf64010a629fe7a82547931 ). I have no scrollbar handles in firefox, but the trough is visible. Other themes work fine.
If I upgrade gtk-3 packages to version 3.20.6-2 from Debian Testing, I get the up/down arrows at the top/bottom of the trough, but still no scroll bar handle visible. terminal and mate theme selector etc have proper scroll bars on both LMDE2's GTK3 version and the new one from Testing.

Is there any Debian release with a compatible GTK3 version? Looks like I can only choose between 3.14 and 3.20, I cannot find version 3.18.

**Comment by JosephMcc** [comment]
A have no idea what's available if you are pulling packages from debian testing.

I'm going to close this. With gtk3, themes pretty much only work with the particular version they are designed for. Right now that means "official" support is only for Mint18 and gtk3.18. There are currently no plans to develop a version for LMDE2 but there should be one for the next version of LMDE.

There is nothing stopping anyone from taking the theme and making a version compatible with LMDE or from pulling out the Cinnamon theme  and making it available on the community site. You should at least change the name to avoid confusion though.
