### ISSUE TITLE
.panel-status-button "widht" instead of "width" in cinnamon.css

### ISSUE THREAD

**Issue by DaveLessnau** [linuxmint/mint-y-theme#24]
I don't know if this is an actual issue.  But, it caught my eye while I was editing the cinnamon.css file under /usr/share/themes/Mint-Y/cinnamon.  Under the .panel-status-button section, "border-width" is spelled as "border-widht".

.panel-status-button {
  border-widht: 0;
  -natural-hpadding: 3px;
  -minimum-hpadding: 3px;
  font-weight: bold;
  color: white;
  height: 22px; }

Again, I don't know if it's a problem.  Maybe it's consistent throughout the system.  I also don't know if the spelling has been copied to other themes' css files.

**Comment by JosephMcc** [comment]
Definitely a typo. Thanks for pointing it out.
