### ISSUE TITLE
dotted lines around buttons and text

### ISSUE THREAD

**Issue by Cyber4** [linuxmint/mint-y-theme#27]
on many buttons (you can use calculator as an example) there's these little dotted lines around EVERYTHING also without any padding whatsoever regardless of if that button is selected.  The dotted lines go directly around the border of the text and looks quite ugly imho.  Is this a feature or a bug or...?

**Comment by JosephMcc** [comment]
I suppose it's a feature. We removed all of the these when we did the Mint-X themes and then have had complaints ever since. People that use mainly the keyboard for navigation use these as an indicator of which widget currently has focus. Because of that I really don't want to remove them.

**Comment by Cyber4** [comment]
The issue is it's not just around the element that's in focus it's around every single element period.  Using the keyboard adds not a second but a THIRD band of dotted lines (on the selected element only).

**Comment by JosephMcc** [comment]
Could you post a screenshot please? Also, what version of MInt and what DE?

**Comment by Cyber4** [comment]
http://imgur.com/a/JTjZC
I'm using linux mint 17.3 XFCE edition.  This occurs in all 3 variations of the theme but I did a temporary fix for the main theme (so I took the screenshot on dark theme) by changing outline-style from dashed to none in gtk.css

**Comment by Cyber4** [comment]
Also after doing this fix the tab thing still works

**Comment by JosephMcc** [comment]
OK, well the theme is designed for Mint18 and gtk3.18. Mint17 uses a much older gtk version and isn't compatible. If you choose to use this theme on older mint versions issues are to be expected. It isn't supported though so please don't open issues here if you are running an incompatible gtk version.
