### ISSUE TITLE
Mint-Y theme suggestion. 

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/mint-y-theme#3]
May I suggest to make "controls" bar grey in Mint-Y Darker Theme? 
Screenshots attached (Paper Theme is used here. Also Ambiance Flat for "windows borders")﻿

I believe grey+black (or light grey + dark grey) looks good :)
![image](https://cloud.githubusercontent.com/assets/19569543/15550324/e4c48ad2-22c1-11e6-93ea-1335d1576a09.png)
![image](https://cloud.githubusercontent.com/assets/19569543/15550325/e4ef254e-22c1-11e6-90c5-ddd01ffcf268.png)

**Comment by clefebvre** [comment]
Hi,

It looks nice, but I don't think it's as nice as using the same color for toolbars and titlebars. We can't support both unfortunately. If you like that style, I would suggest to wait for mint-y to mature, and then fork it into a derivative theme.

**Comment by alxgvr** [comment]
Hi, Clem.

Can you add to Cinnon settings option to remove maximized window headbar?
(like in Unity). I use global menu and window buttons on pannel, so it will
be usefull.

This feature already implemented in Mate and XFCE.

Cinnamon-maximus not working in Mint 18.

пт, 10 июня 2016 г., 4:35 Clement Lefebvre <notifications@github.com>:

**Comment by JosephMcc** [comment]
Not really sure why you are posting this on a closed and totally unrelated issue. Especially when it has nothing to do with the theme. Just for reference there is a proper feature request for this here: https://github.com/linuxmint/muffin/issues/183
