### ISSUE TITLE
Missing borders in controls

### ISSUE THREAD

**Issue by lisuml** [linuxmint/mint-y-theme#30]
I'm trying to get the theme to work on my Manjaro + Cinnamon installation, but when selected, the theme doesn't show borders around controls:

![screenshot from 2016-08-29 09-35-15](https://cloud.githubusercontent.com/assets/6093882/18045695/063f8388-6dcc-11e6-9fe3-a31b8ad0968f.png)

It looks fine with other themes:

![screenshot from 2016-08-29 09-37-18](https://cloud.githubusercontent.com/assets/6093882/18045721/3260871e-6dcc-11e6-853f-4cdc7f2a3b00.png)

It happens almost in all context menus, in some applications and for example in the 'Power off' dialog where buttons have no borders.

**Comment by JosephMcc** [comment]
I assume on Manjaro you are using gtk3.20?

**Comment by lisuml** [comment]
Actually I have both gtk3 and gtk2 installed:

gtk2 2.24.30-3
gtk3 3.20.9-1

**Comment by JosephMcc** [comment]
You are better off using Arc-theme on 3.20
https://github.com/linuxmint/mint-y-theme/issues/18
