### ISSUE TITLE
Mint-Y grey

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/mint-y-theme#31]
Hi. Would be great to see new Mint-Y theme, using Grey color (like Paper theme).

Here I use Paper for windows, and Ambiance-Flat for headbars.
I like Idea to use dark headbars, grey navigation pannel and white background.
If Mint-Y grey will appear  - I could mix all three for my taste. 

![grey](https://cloud.githubusercontent.com/assets/19569543/18066783/8b45b9f0-6e42-11e6-8485-4cdae1179899.png)

**Comment by JosephMcc** [comment]
Please don't keep opening the same request
https://github.com/linuxmint/mint-y-theme/issues/3
