### ISSUE TITLE
Bug in Linux Mint 17.3 (theme is not correct)

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/mint-y-theme#32]
Hi, tried to set Mint-Y theme for Controls and got this:

![mnty](https://cloud.githubusercontent.com/assets/19569543/18067133/1f240be4-6e44-11e6-8690-d90bd8aecc92.png)

For Desktop and Window borders works fine.

**Comment by JosephMcc** [comment]
The theme only supports gtk3.18. There is no plan to support other versions. Such as gtk3.10 used in Mint17.
