### ISSUE TITLE
Window white backgrounds are merging 

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/mint-y-theme#33]
I Run Mint 18 in Virtual Box.
Noticed, that there are no shadows and borders around windows.
So white backgrounds of different windows are merged 

![y](https://cloud.githubusercontent.com/assets/19569543/18070326/0fa59bbe-6e5e-11e6-9334-55cfdd2b82bc.png)

![y2](https://cloud.githubusercontent.com/assets/19569543/18070391/8216d9b0-6e5e-11e6-99ee-bfc35ce63221.png)

Sorry for bad English.

**Comment by JosephMcc** [comment]
From your screenshot it looks like you are running Cinnamon. This is not an issue with the theme. The fact that you have no shadows around your windows means there is some issue with VBox and Cinnamon/Mint or something else.
