### ISSUE TITLE
I can't see the borders

### ISSUE THREAD

**Issue by alejandrosobko** [linuxmint/mint-y-theme#35]
Hello, I'm using Linux mint 18 cinnamon with mint-y theme applied. 
I have the system updated. But [this fix](https://github.com/linuxmint/mint-y-theme/issues/8) is not applied until I restart Cinnamon. When I start my pc, I don't see the borders, like the image uploaded,
but when i restart Cinnamon I can see the borders working fine.

![cap](https://cloud.githubusercontent.com/assets/11604761/18411556/f3312836-774f-11e6-8803-6e83a5ee2d20.png)

**Comment by JosephMcc** [comment]
Your issue isn't theme related. The fix you linked to was for tiled windows. You should see window shadows being drawn on non-tiled windows which doesn't seem to be the case for you. That has nothing to do with the theme.

**Comment by alejandrosobko** [comment]
@JosephMcc How I can fix this? I want to see the borders...

**Comment by JosephMcc** [comment]
I'm not sure. Someone else reported a similar issue here in vbox: https://github.com/linuxmint/mint-y-theme/issues/33

My guess would be it's some sort of graphic driver issue.
