### ISSUE TITLE
Mint-Y nm-applet notification text colour

### ISSUE THREAD

**Issue by BWhitten** [linuxmint/mint-y-theme#36]
The notifications from network manager in the Mint-Y theme have barely readable text, attached is an example.
![notification](https://cloud.githubusercontent.com/assets/962974/18412712/ce3ae97a-778d-11e6-96ff-361babda3a26.png)
This line appears to be the culprit: https://github.com/linuxmint/mint-y-theme/blob/master/src/cinnamon/sass/_common.scss#L827
If I remove that specific color it reverts to the normal text color with good contrast, but I am not sure how this may effect other themes or notifications.

**Comment by JosephMcc** [comment]
Thanks. I'll look into it.
