### ISSUE TITLE
Theme doesn't support GTK 3.20

### ISSUE THREAD

**Issue by mhsabbagh** [linuxmint/mint-y-theme#37]
Hello.

The theme doesn't support GTK 3.20, unlike the original Arc theme which does.

Please see some attached screenshots to see some problems, this is Cinnamon 3.0.7 and Nemo on Fedora 24.

![screenshot from 2016-09-30 20-04-52](https://cloud.githubusercontent.com/assets/1293003/19000049/2de3fbb2-8749-11e6-8c98-11ec8a98c361.png)

**Comment by JosephMcc** [comment]
This has been brought up multiple times:
https://github.com/linuxmint/mint-y-theme/issues/2
https://github.com/linuxmint/mint-y-theme/issues/18
https://github.com/linuxmint/mint-y-theme/issues/30
