### ISSUE TITLE
hover favorites box in menu with Mint-Y theme isn't visible

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/mint-y-theme#38]
When you hover over the favorites in the menu, you should be able to see over which favorites app you are hovering right now (like in this image hovering over firefox):
![bildschirmfoto vom 2016-10-02 15-32-37](https://cloud.githubusercontent.com/assets/8415124/19020932/25e46c3a-88b6-11e6-9c15-c8c09d8930a2.png)

When using Mint-Y theme I can't see where I am hovering over:
![bildschirmfoto vom 2016-10-02 15-32-16](https://cloud.githubusercontent.com/assets/8415124/19020938/36c6c4bc-88b6-11e6-8dea-49206c296c04.png)

This is an issue, if you try to navigate with the keyboard through the favorites box.

**Comment by JosephMcc** [comment]
Thanks for pointing it out. I'll see about getting it fixed.
