### ISSUE TITLE
Gimp window buttons bug

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/mint-y-theme#39]
Hi. Noticed, when Mint-Y theme for Controls applied - Maximize window button disappears in Gimp.
Double click on header bar doesn`t maximize window too. 
It doesn't depend on "Window boarders" theme, only on "Controls" (Mint-Y theme for window boarders + Mint-X for Controls works well, no bug).

Mint 18, fresh install. HP laptop.

![screenshot from 2016-10-03 23-46-11](https://cloud.githubusercontent.com/assets/19569543/19053996/72987b02-89ce-11e6-917a-e1dbb4e3ddd5.png)

**Comment by Odyseus** [comment]
Not a Mint-Y theme issue. See [this](https://github.com/linuxmint/Cinnamon/issues/5739).
