### ISSUE TITLE
Mint-Y-Dark login widget needs better contrast for readability

### ISSUE THREAD

**Issue by mmabey** [linuxmint/mint-y-theme#4]
With the Mint-Y-Dark theme selected in Cinnamon, the login window that appears after locking the screen is almost illegible because of the lack of contrast between the color of the text and the color of the window. Here's what it looks like on my machine:
![login_colors_mint-y-dark](https://cloud.githubusercontent.com/assets/1606251/15612844/45ec3f48-23e5-11e6-966d-19629339c89d.png)

I would recommend styling the user's name and username to be the same color as the "Password:" text, which has sufficient contrast in color to be read easily.

**Comment by JosephMcc** [comment]
This isn't an issue with the theme but with cinnamon-screensaver hard coding text colors.
