### ISSUE TITLE
Issue with space between icons in Nemo

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/mint-y-theme#40]
Hi. Noticed strange icon placement in Nemo icons view.
To much free space between them. 
Could it be more tight? 
Reducing distance between elements will allow more content to be displayed in the window  (which is great)

![screenshot from 2016-10-02 21-53-59](https://cloud.githubusercontent.com/assets/19569543/19054124/f3efed02-89ce-11e6-8ac8-2c83dd704fa8.png)
![screenshot from 2016-10-02 21-54-10](https://cloud.githubusercontent.com/assets/19569543/19054128/f75d063c-89ce-11e6-838c-e03d266b7257.png)

**Comment by alxgvr** [comment]
Seems like wrong thread... Can you move it to Nemo thread?

**Comment by JosephMcc** [comment]
You can just repost it on the nemo repo.
