### ISSUE TITLE
Issue with extra space in Menu applet

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/mint-y-theme#41]
Hi. Noticed extra unused horizontal space in Menu window.
Looks weird...

Mint-Y dark. Mint 18.

![screenshot from 2016-10-02 21-24-13](https://cloud.githubusercontent.com/assets/19569543/19054239/889e49d0-89cf-11e6-8a61-fc0d56fd8bb7.png)

**Comment by JosephMcc** [comment]
Not a bug in the theme. You probably have some long file names in the "Recent Files" category that it is expanding to fit.
