### ISSUE TITLE
Strange dotted lines appears everywhere

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/mint-y-theme#42]
Hi. Noticed strange dotted lines appears everywhere in Cinnamon: filemanager, context menus (on top of the list usually), apps like Liber Office...

Same in Solus Budgie desktop. It uses Arc theme which Mint-Y based on...

![line](https://cloud.githubusercontent.com/assets/19569543/19054637/535e2e96-89d1-11e6-8fe6-ec46607822af.png)

**Comment by mtwebster** [comment]
This is a new..er.. 'feature' of the Gtk3 toolkit - it shows when you're in a scrollable view that has more content beyond the edge where those dots are... for instance, those dots are saying 'you can scroll up' - they'll disappear when you scroll to the top of the view.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/mint-y-theme/issues/14

**Comment by alxgvr** [comment]
Insane.

вт, 4 окт. 2016 г., 0:30 JosephMcc <notifications@github.com>:
