### ISSUE TITLE
Make window edges more rounded, please.

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/mint-y-theme#43]
One thing I literally hate about Arc theme - razor sharp window edges.
Like you can cut your finger if you touch it...

I like more traditional rounded edges like good old Mint-X theme, Ambiance, OsX, many others...
I understand that Mint is looking for new modern look. But, please, not so radical...

I would like to ask Mint team to redraw window edges in Mint-Y theme in traditional rounded way.
Mint-Y is custom Arc theme? Make it less Arc - more custom ;) 

![windowedges](https://cloud.githubusercontent.com/assets/19569543/19055130/98248e24-89d3-11e6-9d0d-ba17ad06a1de.png)

**Comment by JosephMcc** [comment]
You added this to the design discussion issue which was probably the better place. Closing this since we don't really need it in two places.
