### ISSUE TITLE
Can not undecorate window (help needed)

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/mint-y-theme#44]
Hi. I need to undecorate maximized window.
I use this guide to edit matacity-theme file: http://www.webupd8.org/2011/05/how-to-remove-maximized-windows.html

It worked well with Ambiance theme, which I used previously. 
But it does not work with Mint-Y.

There are two files in metacity-1 folder: metacity-theme-2 and metacity-theme-3.
I edit both. Here are the lines:

> frame_geometry name="max" title_scale="medium" parent="normal" rounded_top_left="false" rounded_top_right="false"
> 	distance name="left_width" value="0" /
> 	distance name="right_width" value="0" /
> 	distance name="left_titlebar_edge" value="0"/
> 	distance name="right_titlebar_edge" value="0"/
> 	distance name="title_vertical_pad" value="2"/
> 	distance name="bottom_height" value="1" /
> /frame_geometry

I make like this:

>  frame_geometry name="max" **has_title="false"** title_scale="medium" parent="normal" rounded_top_left="false" rounded_top_right="false"
> 	distance name="left_width" value="0" /
> 	distance name="right_width" value="0" /
> 	distance name="left_titlebar_edge" value="0"/
> 	distance name="right_titlebar_edge" value="0"/
> 	distance name="title_vertical_pad" value="**0**"/
>         **border name="title_border" left="0" right="0" top="0" bottom="0"/
>         border name="button_border" left="0" right="0" top="0" bottom="0"/**
> 	distance name="bottom_height" value="**0**" /
> /frame_geometry
> 

Then, reload theme in Settings.
Nothing realy changing. Header bar is still there.

What I doing wrong? Or something wrong with theme?

**Comment by JosephMcc** [comment]
This isn't an issue with the theme and github isn't really a help forum. Another user is helping you on a Cinnamon issue you opened. Your best bet for help with would be the linux mint forums.
