### ISSUE TITLE
Problem in Mint-Y theme and controls rendering

### ISSUE THREAD

**Issue by mehdi1902** [linuxmint/mint-y-theme#46]
Hi,
When I use Mint-Y theme(specially Mint-Y controls), I get a bad view of it
![image](https://cloud.githubusercontent.com/assets/6816535/19758766/8c4ddec8-9c36-11e6-9619-629944386296.png)
Attend to menu bar in above image and buttons in the below.
![image](https://cloud.githubusercontent.com/assets/6816535/19758792/b8973ad8-9c36-11e6-9d14-a10281187769.png)

But if I use Adwaita everything seems well :)

I copied Mint-Y files from another(well working) system and it didn't work for me.
I have this problem with Mint-X too.

**Comment by JosephMcc** [comment]
What version of gtk are you using?

**Comment by mehdi1902** [comment]
It's the default version that installed in Mint18(Sarah) and I think its gtk3.

I wanted to install Gnome on my Mint but after installed it, I had issue with my system so I reinstall mdm and make it default. after that Mint-Y and Mint-X couldn't render well :)

**Comment by Odyseus** [comment]
Hello, everybody.

@mehdi1902: what JosephMcc is asking you is what version of gtk3 is installed in your system. Run this command in a terminal: `dpkg -s libgtk-3-0 | grep '^Version'`. If the reported version is 3.20 or 3.22, then that's your problem. None of the themes that you installed from Spices supports gkt3 3.20+ (I didn't try the new ones). This was reported numerous times  (#2, #18, #30, #37).

**Comment by mehdi1902** [comment]
@Odyseus 
Thanks for your reply, the result of the command is:

> Version: 3.20.8-1ubuntu0~ppa1

It's 3.20 unfortunately. When I installed the OS for the first time everything was OK and these problems  occurred after trying to install Gnome desktop. I installed this version of OS(Sarah) on another systems and it's OK :-(

**Comment by Odyseus** [comment]
@mehdi1902 

You could simply install a theme that is compatible with gtk3 3.20+. The [Arc-theme](https://github.com/horst3180/Arc-theme) (from which the Mint-Y theme is based on) is very similar to Mint-Y and it's compatible with 3.20+. There is also the [Adapta-gtk-theme](https://github.com/adapta-project/adapta-gtk-theme).

You could also revert back to gtk3 3.18. But it's better that you ask for assistance with that on [Mint forums](https://forums.linuxmint.com/index.php).

**Comment by mehdi1902** [comment]
@Odyseus 
Thanks for your advice :) Your suggested themes are beautiful and what I want ;-)
Now I know about compatibility of a theme and gtk that I didn't know before :-D

thanks a low ;-)
