### ISSUE TITLE
Adding borders highlight to buttons or solving problem with mint-x buttons compability.

### ISSUE THREAD

**Issue by DMantis** [linuxmint/mint-y-theme#48]
Mint-Y theme is perfect except active buttons highlight. It looks like it was designed with mouse-using in mind. 

I'm using my computer only with keyboard really often and I find out that button highlight in shutdown menu window and password-input window is awful. I always need to gaze into menu to see which button is now active to check it with keyboard, not mouse. That's because Mint-Y button highlight style not really notable.

There is no such problem with Mint-X theme, the active button always has very notable green borders highlight. I really like the other parts on Mint-Y theme, so I've thought about using it with Mint-X buttons. 

As far choosing different parts of themes is going out-of-box I've thought that 2 default themes should be fully compatible with each other. But they are not. There is an issue at least with firefox tabs here using Mint-Y theme with Mint-X buttons.
![firefox](https://cloud.githubusercontent.com/assets/9536869/20024670/8aeb42a6-a301-11e6-8354-93832decf4b5.png)

I hope you will fix this issue and add different flavour of Mint-Y buttons with better highlight.

Good design should be convenient to use, not being only good-looking.

**Comment by JosephMcc** [comment]
Did you close and restart Firefox after changing themes? Firefox often shows like that on theme changes until it is restarted.

**Comment by DMantis** [comment]
Oh, that's true. Restarting firefox solves the problem with different styles. Sorry for that.

But, anyway, you could count this issue as a wish of official flavour of mint-y to keyboard users in mint spices. 

And thank you for the great work)

**Comment by JosephMcc** [comment]
The strange thing is if you arrow left or right on the shutdown dialog, the dashed line focus indicator shows up. Not sure why it doesn't when first opened.

**Comment by DMantis** [comment]
That's right, but even this dash line not very notable and I need a few seconds to ensure that I check the right button. It really depends on screen, actually. I suppose that UI should be intuitive and work well without these few seconds to realize such automatic deals.

No matter what quality of the screen and what contrast/brightness settings are used.

**Comment by JosephMcc** [comment]
These types of discussions can go here: https://github.com/linuxmint/mint-y-theme/issues/13
