### ISSUE TITLE
No borders xfwm4

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mint-y-theme#5]
There are no borders alongside window frame. Also resize handlers appear on titlebar in the wrong positions.
**Update:** the handlers were appearing in incorrect positions due to some virtualbox bugs. So only borders should be added. I guess 3 pixels wide, as in Mint-X

**Comment by JosephMcc** [comment]
Since they are meant for Mint18 and there isn't a version of Mint18 Xfce yet they haven't been tested to be honest. Mate and Cinnamon versions are released first and have been the focus up to this point.

**Comment by clefebvre** [comment]
I'll try to get an early Xfce ALPHA ready for developers.

**Comment by wallacesilva** [comment]
i have the same problem. i solved with this: https://github.com/horst3180/arc-theme/issues/7#issuecomment-161710585

but i changed the file gtk3 but i search a solution in file xfwm4

**Comment by Yanpas** [comment]
@wallacesilva it's a different issue and it occurs on old gtk. On ubuntu 14.04 e.g.. In LM18 there is no such issue

**Comment by wallacesilva** [comment]
@Yanpas ok, im using linux mint 17.3 now. on final release i will upgrade.  but thanks about this issue :D
