### ISSUE TITLE
Mint-Y Menu Separator item is invisible

### ISSUE THREAD

**Issue by vassilisw** [linuxmint/mint-y-theme#50]
**Menu separator** items are not showing. There's just a space instead between menu items that supposed to be clearly separated. 
This is always the case and very easy to reproduce.

**Same** thing happens in **panel** menus (plus volume, network, etc applets): No menu separators when everything is set to Mint-Y

![mint menu separator 1](https://cloud.githubusercontent.com/assets/16954451/20968021/eb9cd23e-bc8a-11e6-91f2-dc44dfeeb0d5.png)
![mint menu separator 2](https://cloud.githubusercontent.com/assets/16954451/20968020/eb98e16a-bc8a-11e6-8699-baea1af13b6a.png)

**Comment by JosephMcc** [comment]
This isn't a bug. That's how it's supposed to be.

**Comment by vassilisw** [comment]
There is no other OS theme in this planet that has no separators just because it is flat. 
I am disappointed to hear that this is how it's supposed to be.
Are you totally sure?
