### ISSUE TITLE
Selection color same as background color

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/mint-y-theme#55]
Selecting the URL in the Chrome address bar is now difficult, since something changed the selection color to be exactly the same as the address bar background.

![image](https://cloud.githubusercontent.com/assets/1702193/24174904/aacf3b74-0e93-11e7-9765-546189271bf3.png)

Interestingly, on Mint-Y light, the selection background color for text stays dark grey, but the Chrome address bar selection color turns white like the background so it's _still_ hard.

These selection colors used to be green and something recently changed them to dark grey. 

Where can I change this back?

**Comment by JosephMcc** [comment]
Web browsers have a tendency to handle themes the way they want. Dark themes are notoriously problematic and there isn't much we can do about it.
