### ISSUE TITLE
GTK 3.20 compatibility

### ISSUE THREAD

**Issue by Zulgrib** [linuxmint/mint-y-theme#56]
Mint-Y theme use deprecated functions, making it render incorrectly on up to date systems using GTK 3.20 or superior.

**Comment by JosephMcc** [comment]
Again https://github.com/linuxmint/mint-y-theme/issues/37

**Comment by Zulgrib** [comment]
Was closed without fix or workaround like this one, and all mentioned issues in #37 were closed without resolution too.
