### ISSUE TITLE
Mint Y Dark Theme makes posting on Google+ social network unreadable. [screenshot included]

### ISSUE THREAD

**Issue by jessedubord** [linuxmint/mint-y-theme#57]
See the screenshot at this link, here: [https://www.dropbox.com/s/ybnwsw4af2sjxi9/mint%20y%20dark%20theme%20issue%20with%20google%20plus.png?dl=0](https://www.dropbox.com/s/ybnwsw4af2sjxi9/mint%20y%20dark%20theme%20issue%20with%20google%20plus.png?dl=0)

When using Google+ on Firefox with the "Mint-Y-Dark" theme enabled, trying to post or write text in a text field on plus.google.com shows up a light gray and color, and is difficult to read.

Expected appearance would be a legible, darker text, IMO.

Bug discovered while using:
Linux Mint 18.1 x64
Cinnamon 3.2.7 desktop environment.

**Comment by JosephMcc** [comment]
Sorry but currently there isn't much that can be done about this. It has always been a problem with full dark themes in web browsers. Believe me I'll be one of the happiest people around when apps like Firefox handle this sort of thing better.
