### ISSUE TITLE
Mint-Y-Darker theme doesn't seem to look correct

### ISSUE THREAD

**Issue by rfquerin** [linuxmint/mint-y-theme#59]
The window pane background remains dark when I use the Mint-Y-Darker theme. So there is very little difference between the Mint-Y-Darker and Mint-Y-Dark theme on my system. I think the Darker variant used to have a while panel background (in the file exporer for instance). All other mint-y variants seem to look correct. I've even installed the Arc-Darker theme and it too has a dark window pane background. Is there something I could have screwed up somewhere? This is on Mint 18.1.

**Comment by JosephMcc** [comment]
I've not seen this and I use the themes daily. Does it happen in all apps or just certain ones?

**Comment by saulo16v** [comment]
Hi, just for the record, it looks like the option "Use a dark theme variant when available in certain applications" is causing this behavior for Mint-Y-Darker. If I select the mentioned option there's no big difference between Mint-Y-Darker and Mint-Y-Dark as seen on the following screenshots:
Selected option:
![use-a-dark-theme-variant](https://user-images.githubusercontent.com/6633092/34582244-2f19ea5c-f18b-11e7-9d0d-e29f71cb39ef.png)

Mint-Y-Darker
![mint-y-darker](https://user-images.githubusercontent.com/6633092/34582265-3f4fcaea-f18b-11e7-9372-3a9870920f91.png)

Mint-Y-Dark
![mint-y-dark](https://user-images.githubusercontent.com/6633092/34582275-486b3e34-f18b-11e7-85ea-9e42a6fb4d6c.png)
