### ISSUE TITLE
There is a color problem in firefox tab (screenshots)

### ISSUE THREAD

**Issue by ebretteville** [linuxmint/mint-y-theme#6]
As you can see in the screenshots, there is a little graphical bug. Nothing important, I could not wait testing Mint-Y and give my feedbacks

![capture du 2016-06-06 14 21 45](https://cloud.githubusercontent.com/assets/3687099/15822110/21537d10-2bf4-11e6-92fb-6147e7e5ad9a.png)
![capture du 2016-06-06 14 22 08](https://cloud.githubusercontent.com/assets/3687099/15822111/2157ec4c-2bf4-11e6-9e06-9f46e0c73775.png)

**Comment by JosephMcc** [comment]
Firefox doesn't always update properly when changing themes. This will happen with most themes and is an issue with Firefox. Closing and restarting Firefox will fix the issue. This sort of thing happens with a lot of applications.
