### ISSUE TITLE
contrast issues using Mint-Y-Dark

### ISSUE THREAD

**Issue by random640** [linuxmint/mint-y-theme#61]
Distro: Linux Mint 18.2 Beta (downloaded 10.6.17), all updates installed
Window Controls theme: Mint-Y-Dark
Window Border theme: Mint-Y-Dark

**Little contrast in Software Manager**
The summary text(the text appearing under the application name) in the software manager has a gray font color that provides low contrast to the dark gray background. When the application is selected this is not a problem. This small contrast makes the description difficult to read, especially for people with reduced vision. This also applies to the number of ratings.

<img width="761" alt="skjermbilde 2017-06-11 kl 14 06 07" src="https://user-images.githubusercontent.com/21174594/27010880-58296974-4eaf-11e7-9485-fdd589e4a59b.png">

**No window border**
Using both Mint-Y-Dark for window borders and controls the windows does not have a visible border. When the overlaying windows both have the same background color (such as the default Terminal application) the windows becomes difficult to distinguish.
<img width="873" alt="skjermbilde 2017-06-11 kl 14 10 42" src="https://user-images.githubusercontent.com/21174594/27010896-ca1e1c78-4eaf-11e7-9d46-127cf01245a5.png">

**Comment by JosephMcc** [comment]
> Little contrast in Software Manager

This is a known issue with the Software Manager. Those colors are hardcoded and the theme cannot change them.  If you are going to use a full dark theme be prepared to run into some of this type of thing. Some apps make the assumption that a theme will be certain colors and hard code colors in.

> No window border

I don't now how you are getting that. You don't say what DE you are using. Possibly an issue with running in VirtualBox? I looks like no compositing is enabled. It looks like this here:

![selection_015](https://user-images.githubusercontent.com/2231759/27013042-c657be56-4e90-11e7-9b4b-a094ef1929e7.png)
