### ISSUE TITLE
Mint-y-Dark theme forcing panel into 30px+ mode

### ISSUE THREAD

**Issue by calexil** [linuxmint/mint-y-theme#64]
![screenshot at 2017-07-03 13-42-28](https://user-images.githubusercontent.com/3487071/27837810-90632124-60b4-11e7-8b97-74d6195e7625.png)

**Comment by JosephMcc** [comment]
This report is a bit useless since you don't provide even basic information like desktop environment, version, icons being used, etc. I've not seen this issue in my own testing.

**Comment by calexil** [comment]
@JosephMcc  updated, reopen

**Comment by calexil** [comment]
how do I unlock the color tab in appearance... and why was it removed?

**Comment by JosephMcc** [comment]
Seems to be fine here with all the included icon sets.

**Comment by calexil** [comment]
It is occuring with included icons as well. hexchat, and mintupdate icons in the notification area are huge, everything else is the right size

**Comment by calexil** [comment]
just because something does not affect you, does not mean it is not an issue.

pls reopen

**Comment by JosephMcc** [comment]
I tested this under the included mint themes and with a bunch of themes from the mate-themes package. They all behave the same.

**Comment by calexil** [comment]
something is amiss ... ill get you images of the defaults messing up as well tonight

for now, please reopen this so I dont lose it

**Comment by JosephMcc** [comment]
Your missing the point. These things are happening with all themes as far as I can see. It isn't issue with the Mint-Y theme.

**Comment by calexil** [comment]
you're* missing the point, they occur with defaults as well... Ill show you tonight when I get home from work

**Comment by JosephMcc** [comment]
Since you refuse to actually read or pay attention, I'm locking this. It happens in all themes I tried. That points to it not being an issue with Mint-Y.
