### ISSUE TITLE
Mint-y theme conflicts with mate-panel item "menu bar" causing icon sizing to be larger than it should.

### ISSUE THREAD

**Issue by calexil** [linuxmint/mint-y-theme#66]
Steps to replicate this issue:

Mint 18.2 MATE

select a flavor of mint-y theme(mint-y-dark was used in my instance)

any icon pack is fine including defaults, the behavior is icon-independent 

set panel to top position, 24px width, remove base menu and "add item" "menu bar"(the old gnome 2.0 style menu with apps, places, system)

[Since definitive evidence was impossible earlier, I made a video... because it's hard to argue with a video ;)](https://www.youtube.com/watch?v=1aikR3Am7O0)

**Comment by calexil** [comment]
great work @JosephMcc  do I need to do a dkpg build or will this be rolled into a release soon?

**Comment by calexil** [comment]
also sorry for being a dickwad earlier.. I was frustrated

**Comment by JosephMcc** [comment]
I don't handle tagging or deciding when these get pushed out. If you want to test it you'll need to build it yourself. I imagine it will get out fairly soon.

**Comment by calexil** [comment]
okay.
