### ISSUE TITLE
mint-y theme not obeying mate panel bg transparency setting

### ISSUE THREAD

**Issue by calexil** [linuxmint/mint-y-theme#68]
the window list applet for the mate panel does not abide by the bg transparency setting under mint-y theme

![screenshot at 2017-07-09 21-09-01](https://user-images.githubusercontent.com/3487071/27999461-64c2154e-64eb-11e7-98e5-e87b4be8c33d.png)

Steps to replicate this issue:

Mint 18.2 MATE

select a flavor of mint-y theme(mint-y-dark was used in my instance)

any icon pack is fine including defaults, the behavior is icon-independent 

set panel to top position, 24px width, remove base menu and "add item" "menu bar"(the old gnome 2.0 style menu with apps, places, system)

Set the panel bg color to black and opacity to ~30%

**Comment by JosephMcc** [comment]
This should be much improved by https://github.com/linuxmint/mint-y-theme/commit/8d9d3a10c681d94c69566900dd63c37456ac6de4

**Comment by calexil** [comment]
cool, good stuff @JosephMcc
