### ISSUE TITLE
Mint-y theme window list padding at 24px is cutting off top and bottom of application icons

### ISSUE THREAD

**Issue by calexil** [linuxmint/mint-y-theme#69]
![screenshot at 2017-07-09 21-19-23](https://user-images.githubusercontent.com/3487071/27999568-96bd35d2-64ec-11e7-8f0c-8921dd8e0bb3.png)

Steps to replicate this issue:

Mint 18.2 MATE

select a flavor of mint-y theme(mint-y-dark was used in my instance)

any icon pack is fine including defaults, the behavior is icon-independent 

set panel to top position, 24px width, remove base menu and "add item" "menu bar"(the old gnome 2.0 style menu with apps, places, system)

**Comment by JosephMcc** [comment]
Fixed by https://github.com/linuxmint/mint-y-theme/commit/08e07a9229a48524032eedddb5c3d4b203f17049

**Comment by calexil** [comment]
awesome work @JosephMcc  I'll look for the patch
