### ISSUE TITLE
Panel Handle With is extremely small (only one pixel)

### ISSUE THREAD

**Issue by Robert42** [linuxmint/mint-y-theme#7]
It's very hard to catch it, making using some software really painfull.

![screenshot from 2016-06-06 23 17 49](https://cloud.githubusercontent.com/assets/488876/15838257/5523e942-2c3d-11e6-93d3-126906f7008a.png)

(The software on the screenshot is Glade version 3.16.1)

**Comment by JosephMcc** [comment]
There are now two styles of pane-separator in gtk. A normal and a "wide" style. It's really up to the application what it uses. What distro and gtk version are you running Mint-Y with?

**Comment by Robert42** [comment]
I am using *Linux Mint 17.3 Cinnamon 64-Bit* with Gtk 3.10.8

**Comment by JosephMcc** [comment]
Well the theme is built for MInt18 and gtk3.18. I surprised it's even working as well as it is. It isn't meant to work on Mint17.

**Comment by Robert42** [comment]
well good work then ;)
I assume I will have to wait for the beta to be able to test the theme on linuxmint 18 with an iso?

**Comment by JosephMcc** [comment]
That would be the best bet, yes.
