### ISSUE TITLE
Missing Controls with Ubuntu

### ISSUE THREAD

**Issue by BandonRandon** [linuxmint/mint-y-theme#70]
I run Cinnamon and Mint-y on both Linux Mint 18.2 and Ubuntu 17.04 with different machines. After seeing the Mint-Y update (1.2.1) on my Native Mint box I manually updated the Ubuntu Machine. However, immediately I started seeing some missing padding and control issues with Mint-Y controls. 

One of the most annoying is that highlighting fails in Firefox. 

Other themes work as expected such as Menta which I'm using now while trying to figure out the problem with Mint-Y.

I have tried various versions of Mint-Y and tried both compiling locally and downloading the official `.deb` files from `packages.linuxmint.com`

```
/usr/share/themes$ cd Mint-Y && ls -la
total 36
drwxr-xr-x  8 root root 4096 Jan 25 03:18 .
drwxr-xr-x 33 root root 4096 Jul  9 23:22 ..
drwxr-xr-x  4 root root 4096 Jan 25 03:34 cinnamon
drwxr-xr-x  4 root root 4096 Jan 25 03:18 gtk-2.0
drwxr-xr-x  3 root root 4096 Jan 25 03:34 gtk-3.0
-rw-r--r--  1 root root  252 Jan 25 03:34 index.theme
drwxr-xr-x  2 root root 4096 Jan 25 03:34 metacity-1
drwxr-xr-x  2 root root 4096 Jan 25 03:18 xfce-notify-4.0
drwxr-xr-x  2 root root 4096 Jan 25 03:34 xfwm4
```

Any help or guidance would be great here. 

![screenshot_09-07-2017-22 47 50](https://user-images.githubusercontent.com/150348/28004581-7215bb4c-64fa-11e7-9240-c35e88753b34.png)
![screenshot_09-07-2017-22 43 16](https://user-images.githubusercontent.com/150348/28004601-997aa65c-64fa-11e7-84d2-754e0cd71b00.png)

![screenshot_09-07-2017-23 04 27](https://user-images.githubusercontent.com/150348/28004661-0125587e-64fb-11e7-918c-cc72404dbc67.png)

**Comment by BandonRandon** [comment]
System Info: https://gist.github.com/anonymous/ba9e99475d862bdd04aebbe99718633a

**Comment by JosephMcc** [comment]
If you search closed issues this has been brought up many times. One such example https://github.com/linuxmint/mint-y-theme/issues/18

The themes are built for Mint. They will be updated when Mint needs them. That should actually be before too much longer.
