### ISSUE TITLE
Pale Moon Icons

### ISSUE THREAD

**Issue by Ascrod** [linuxmint/mint-y-theme#75]
The Mint-Y icon theme appears to override the icons for Pale Moon, a browser I have installed. The new icons look like something for Battle.net. The browser ships with no icon themes other than the default set, and is not related to Blizzard.

Expected icon shown in Mint-X and other themes:
![palemoon_mint-x](https://user-images.githubusercontent.com/32915892/32147013-509a0f4a-bcb6-11e7-86d7-1cd5546c54a3.png)

Icon shown in Mint-Y:
![palemoon_mint-y](https://user-images.githubusercontent.com/32915892/32147015-5388a5cc-bcb6-11e7-8fcd-8d61cb2408aa.png)

Running Mint 18.2.

**Comment by JosephMcc** [comment]
This actually belongs here: https://github.com/linuxmint/mint-y-icons
Most users want an icon theme to cover as many application icons as possible for the most consistent style. If you just feel the design for that particular is icon is poor, that's ok. Pull requests are always welcome :)

**Comment by wolfbeast** [comment]
Pale Moon project owner here: the problem isn't about the design being poor, it's about it not being the proper branding image for the browser at all, and in fact it's an existing icon from a different software vendor.
