### ISSUE TITLE
GIMP shows inconsistent white border

### ISSUE THREAD

**Issue by orschiro** [linuxmint/mint-y-theme#77]
Not sure what can be done with it. But I noticed this small inconsistency. 

With Mint-X:

![image](https://user-images.githubusercontent.com/170947/34676962-dee0deb8-f48e-11e7-84fd-d3f80d223b09.png)

With Mint-Y:

![image](https://user-images.githubusercontent.com/170947/34677050-34af1756-f48f-11e7-84a4-2f82ed1a2c04.png)

**Comment by NikoKrause** [comment]
Looks normal here on Mint 18.3
