### ISSUE TITLE
No scrollbar in the (already cumbersome) Thunderbird 'customise' menu

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-y-theme#79]
With the Mint-Y theme:

![image](https://user-images.githubusercontent.com/9998846/35259272-d35af73a-fffc-11e7-9b2b-269487c0ac20.png)

With Mint-X:

![image](https://user-images.githubusercontent.com/9998846/35259285-e326a876-fffc-11e7-8ca3-71d20aec7f65.png)

**Comment by NikoKrause** [comment]
I do see a scrollbar with Mint-Y in Mint 18.3

**Comment by JosephMcc** [comment]
Yep works fine here under Mint19 as well.
