### ISSUE TITLE
Mint 18 Cinnamon: No borders for tiled windows

### ISSUE THREAD

**Issue by AlbertJP** [linuxmint/mint-y-theme#8]
Mint-Y bug or Cinnamon bug?

In this screenshot I am missing a border between the tiled window at the right and the maximised window on the background.
![mint-y-bugs](https://cloud.githubusercontent.com/assets/1248033/15872391/bcc56e1c-2ce8-11e6-9a59-1348f9be1cd6.png)

This screenshot was taken in a live session of Mint 18, 32-bit Cinnamon edition with Cinnamon 3.0.5.

**Comment by JosephMcc** [comment]
This should be fixed by: https://github.com/linuxmint/mint-y-theme/commit/d05812941e97cb637744762dbc4f82032d70bba6

**Comment by alejandrosobko** [comment]
I have the system updated. But this fix is not applied until I restart Cinnamon. When start my pc, I don't seed the borders, like the image uploaded at head, but when i restart Cinnamon I can seed the borders working fine.
