### ISSUE TITLE
Windows controls do not scale with DPI

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-y-theme#80]
To reproduce:

1. Choose Mint-Y as control font.
2. Change DPI to 'high'.
3. Observer very small close, minimize etc. icons.
4. Change window title font and observe that the close etc. icons remain the same size.

Mint 18.3 x64 Cinnamon.

EDIT: ah, the scaling seems to take effect after a _reboot_, though one is not prompted to reboot.

**Comment by JosephMcc** [comment]
This is a known issue and has nothing to do with the theme. Restarting Cinnamon is sometimes needed for everything to properly update.
