### ISSUE TITLE
Mint-Y and all inbuilt 'window border' themes save 'high contrast' do not scale with titlebar

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-y-theme#81]
Mint 18.3.

To reproduce:

- System Settings -> Fonts -> Windows title font -> Set to a value some 50% higher than the default.
- Observe (possibly after a reboot or logoff) how the window controls (close, maximise, etc.) do not scale with the title font.

**What should happen**

_Either the controls should scale with the font or the user should be asked whether he/she wants that to happen._ Or such seems a good idea to me.

**Additional information**

The high contrast theme, which emerges as something of a hero here, is buggy in another respect: its hover colouration varies between windows and sometimes makes control icons almost totally black. This matters (at least) because at present that theme is the only inbuilt theme that avoid the scaling problem.

I can provide screenshots, at the price of temporarily messing up my hard-won and just-about-usable monitor (font, DPI, themes) display.

**Comment by JosephMcc** [comment]
No they don't. The buttons are imaged based and the window manager doesn't scale them. I don't think that any window manager does.
