### ISSUE TITLE
White buttons hardly visible on xfce-panel with Mint-y theme

### ISSUE THREAD

**Issue by dbeniamine** [linuxmint/mint-y-theme#83]
Hello,

I'm a Debian Xfce4 user and I think that Linux Mint is just beautiful, so I installed the Mint-Y theme from Git, but some buttons were hardly visible on my xfce4-panel, as you can see here : 

![light](https://user-images.githubusercontent.com/2989133/38770326-98ac37ac-4011-11e8-94ee-a1854bec149b.png)

while they were well visible with the Mint-Y-Dark theme : 

![dark](https://user-images.githubusercontent.com/2989133/38770327-9dfe31b0-4011-11e8-9c84-81b26f903cd5.png)

So i've played with the theme and identified the responsible line. So there is a minimalist patch to solve this issue : 

    diff --git a/src/gtk-3.0/gtk.css b/src/gtk-3.0/gtk.css
    index d61f76d..7aa79f4 100644
    --- a/src/gtk-3.0/gtk.css
    +++ b/src/gtk-3.0/gtk.css
    @@ -245,7 +245,7 @@ button {
       border: 1px solid;
       border-radius: 3px;
       padding: 5px 8px;
    -  color: #4a4a4a;
    +  color: #DADADA;
       outline-color: rgba(74, 74, 74, 0.3);
       border-color: #cfcfcf;
       background-color: whitesmoke; }
    diff --git a/usr/share/themes/Mint-Y/gtk-3.0/gtk.css b/usr/share/themes/Mint-Y/gtk-3.0/gtk.css
    index d61f76d..7aa79f4 100644
    --- a/usr/share/themes/Mint-Y/gtk-3.0/gtk.css
    +++ b/usr/share/themes/Mint-Y/gtk-3.0/gtk.css
    @@ -245,7 +245,7 @@ button {
       border: 1px solid;
       border-radius: 3px;
       padding: 5px 8px;
    -  color: #4a4a4a;
    +  color: #DADADA;
       outline-color: rgba(74, 74, 74, 0.3);
       border-color: #cfcfcf;
       background-color: whitesmoke; }

The issue is also in the Mint-Y-Darker theme.

**Comment by JosephMcc** [comment]
Thanks for the report. Git master is still in the process of being updated for gtk3.22. I haven't gotten to testing under Xfce yet. Was getting the core stuff, then Mate, then Xfce. The theme has specific theming for it's panel. I just need to try it under Xfce and update it. Appreciate the feedback though. I'll try to get it soon.

**Comment by JosephMcc** [comment]
Just realized the repo this is on. Mint-Y is now part of mint-themes. It's no longer being updated here.

**Comment by dbeniamine** [comment]
Ok I switched to the new repository, the issue is still present in the new one and my patch still apples (just need to change the src path), should I open a new issue ?

BTW my patch was wrong, it made all buttons white, this patch is way better : 

    diff --git a/src/Mint-Y/gtk-3.0/gtk.css b/src/Mint-Y/gtk-3.0/gtk.css
    index 23a76fa..96842c6 100644
    --- a/src/Mint-Y/gtk-3.0/gtk.css
    +++ b/src/Mint-Y/gtk-3.0/gtk.css
    @@ -3407,6 +3407,9 @@ SynapseGuiViewVirgilio *:selected {
     
     .xfce4-panel.panel {
       background-color: #393939; }
    +  .xfce4-panel.panel button{
    +      color: #DADADA;
    +  }
       .xfce4-panel.panel .button.flat {
         color: #DADADA;
         background-color: rgba(57, 57, 57, 0);

**Comment by JosephMcc** [comment]
Nah. I'll look at getting proper xfce panel support in the next day or two.

**Comment by JosephMcc** [comment]
Ok. Try updating to the newest mint-themes master. Pushed some fixes for this.

**Comment by dbeniamine** [comment]
The Mint-Y theme looks good for me, thanks :+1: 

However the issue is still present on the Mint-Y-Darker
