### ISSUE TITLE
Contrast problem with Mint-Y-Dark, in Thunderbird

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-y-theme#84]
Here's a partial screenshot of Thunderbird (52.7) and specifically its compose window.

![image](https://user-images.githubusercontent.com/9998846/40479038-8a369e38-5f42-11e8-8a6a-cef856aa2621.png)

Note the unreadability of the text on the grey-white buttons.

Here's the same area but with the third-party 'deep dark' theme installed - much better!

![image](https://user-images.githubusercontent.com/9998846/40479074-9ed3f48a-5f42-11e8-89ee-3080a5036c51.png)

This is a shame because in other respects Mint-Y-Dark is functional and beautiful in Thundebird.

System theme settings:

![image](https://user-images.githubusercontent.com/9998846/40478886-26f5beb2-5f42-11e8-8980-4c6ae0b94adc.png)

Mint 18.3 Cinnamon

**Comment by JosephMcc** [comment]
Sorry but there isn't much to be done here. Thunderbird is one of those apps that just sort of does what it wants with the theme.
