### ISSUE TITLE
FEATURE REQUEST: please do releases

### ISSUE THREAD

**Issue by Deuxis** [linuxmint/mint-y-theme#85]
That way we'll be able to automatically pull a given theme version from github archives. This is how for example the Arc theme Portage package works.

I love Linux Mint, but I hate how outdated everything is in the name of stability, so I'd love to make Gentoo/Portage packages for Mint-Y and Mint-Y icons and use them and share them with others

**Comment by JosephMcc** [comment]
Everything in this repo is now part of the mint-themes repo https://github.com/linuxmint/mint-themes  We are no longer updating this one.
