### ISSUE TITLE
No progressbar for MATE OSD's

### ISSUE THREAD

**Issue by bwat47** [linuxmint/mint-y-theme#86]
In the Mate Desktop, the OSD's that pop up when changing volume or screen brightness are supposed to have a progressbar at the bottom.

With other themes this progressbar is shown, but with Mint-Y you can't see the progressbar at all.

I attached screenshots comparing Mint-X and Mint-Y. You can see with Mint-X the bar is shown, but with Mint-Y it's not.

Since Mint-Y is default in mint 19 mate it seems like this should be fixed!
![mint-x](https://user-images.githubusercontent.com/1442520/41501547-8c4d8832-7174-11e8-94a6-b0c9684fb712.png)
![mint-y](https://user-images.githubusercontent.com/1442520/41501548-8c5e50e0-7174-11e8-97ed-9d95e0562cad.png)

**Comment by JosephMcc** [comment]
The Mint-Y-Themes have been moved to mint-themes. This repo is no longer active.

This issue has been fixed on mint-themes master.
