### ISSUE TITLE
Timeshift: excessively small notifications with Mint-Y dark

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-y-theme#87]
Please see [this bug report](https://github.com/teejee2008/timeshift/issues/212#issuecomment-399680862).

Mint 18.3

**Comment by JosephMcc** [comment]
There isn't enough info to go on here. It seems fine to me under Cinnamon. You don't even say what DE you are using.

**Comment by ghost** [comment]
> There isn't enough info to go on here. It seems fine to me under Cinnamon. You don't even say what DE you are using.

I apologise. I am using Cinnamon.

Font settings:

![screenshot from 2018-07-07 14-12-27](https://user-images.githubusercontent.com/9998846/42411201-e0ea7338-81ef-11e8-8da2-31bed14fe3a6.png)

**Comment by JosephMcc** [comment]
I don't know what else you have on your system but that notification doesn't even look like it came from Cinnamon. He says he using notify-send to supply it. You can test yourself in a terminal using `notify-send "hello"`. I don't think it's a theme issue at all.

**Comment by ghost** [comment]
Hi Joseph

My other notify-sends look as they should. So, I've re-opened the bug on https://github.com/teejee2008/timeshift - [here](https://www.virtualbox.org/wiki/Linux_Downloads).

**Comment by JosephMcc** [comment]
Frankly, I doubt this is a timeshift issue either. It looks like you might have something installed that is interfering with notifications.

**Comment by ghost** [comment]
Well, as I say, all my other notifications work. Where might I look for a possible cause, though, please?
