### ISSUE TITLE
HTML Range Input broken in Firefox when using Mint-Y/Mint-Y-Darker

### ISSUE THREAD

**Issue by blainester** [linuxmint/mint-y-theme#9]
(An HTML Range is the slider bar for websites)

[Link to screenshots](http://imgur.com/a/Lg8Pq)
Image 1 is using Mint-X (renders perfectly)
Image 2 is using Mint-Y-Darker (only the selectable part is visible)
Image 3 is using Mint-Y-Dark (renders acceptably, but could be improved a bit)

The range looks identical in Mint-Y and Mint-Y-Darker.

To replicate, create an html file with the following contents:
`<html><body><input type="range" min="0" max="10"></body></html>`

and open in Firefox

**Comment by JosephMcc** [comment]
I'll have to do some digging to figure out how to fix that one. Thanks for providing a nice way to reproduce. Do you run into this somewhere in an actual website?

**Comment by blainester** [comment]
I use the range in a customized [AJAX-Chat](https://github.com/Frug/AJAX-Chat) to control the volume of the sounds.

**Comment by JosephMcc** [comment]
Ok, this proved to be a challenge to figure out what the issue was and get it fixed but it's fixed now by https://github.com/linuxmint/mint-y-theme/commit/55b84af20ad18a3f565a79ba97188894042a9b10
