### ISSUE TITLE
Create hdpi and xhdpi versions of the theme for xfwm4 or provide source file

### ISSUE THREAD

**Issue by Blub86** [linuxmint/mint-y-theme#91]
The Mint-Y, Mint-Y Dark and Mint-Y Darker themes should have hdpi and xhdpi versions for the xfce window manager.
 If someone uses a high definition screen and doesn’t sit directly in front of the screen the buttons and everything are too small to be usable. 
Sadly there is no lossless source provided for the xfwm4 versions, only .xpm files. If files would be included as .svg or another lossless format someone or myself could make those larger versions.

**Comment by JosephMcc** [comment]
Not currently really interested in trying to maintain even more versions of the theme to work around the fact that XFCE doesn't support HiDPI. When it has proper support then we'll look into what's needed.

As for .svg versions of the the assets, we don't have them. If you want to do this yourself, you'll have to create them.
